version: '3.8'

services:
  portfolio_frontend:
    container_name: portfolio-client
    image: devstoni/arcp:0.1.25
    restart: unless-stopped
    ports:
      - $CLIENT_HOST_PORT:80
    stdin_open: true
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_frontend.rule=Host(`portfolio.local`)"
      - "traefik.http.services.portfolio_frontend.loadbalancer.server.port=5173" 

networks:
  net:
    external: False
